name: circle_bottom_navigation
description: An animated, beauty and functional Bottom Navigation Bar you app.
version: 1.0.6
homepage: https://github.com/jeaanlucas/circle_bottom_navigation

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.0.8
  analyzer: ^0.39.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
